[05-Aug-25 01:26:28 - INFO] - ZeMusic.core.mongo - يتم رفع البيانات...
[05-Aug-25 01:26:28 - INFO] - ZeMusic.core.mongo - تم رفع البيانات.
[05-Aug-25 01:26:28 - INFO] - ZeMusic.core.dir - تم اكتمال التحميل.
[05-Aug-25 01:26:28 - INFO] - ZeMusic.core.git - Git Client Found [VPS DEPLOYER]
[05-Aug-25 01:26:28 - INFO] - ZeMusic.misc - Local Database Initialized.
[05-Aug-25 01:26:28 - INFO] - ZeMusic.core.bot - يتم تشغيل البوت..
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/workspace/ZeMusic/__main__.py", line 89, in <module>
    asyncio.get_event_loop().run_until_complete(init())
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/asyncio/base_events.py", line 719, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/workspace/ZeMusic/__main__.py", line 48, in init
    await sudo()
  File "/workspace/ZeMusic/misc.py", line 62, in sudo
    sudoers_doc = await sudoersdb.find_one({"sudo": "sudo"})
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/synchronous/collection.py", line 1755, in find_one
    for result in cursor.limit(-1):
                  ~~~~~~~~~~~~^^^^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/synchronous/cursor.py", line 1284, in __next__
    return self.next()
           ~~~~~~~~~^^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/synchronous/cursor.py", line 1260, in next
    if len(self._data) or self._refresh():
                          ~~~~~~~~~~~~~^^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/synchronous/cursor.py", line 1208, in _refresh
    self._send_message(q)
    ~~~~~~~~~~~~~~~~~~^^^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/synchronous/cursor.py", line 1102, in _send_message
    response = client._run_operation(
        operation, self._unpack_response, address=self._address
    )
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/synchronous/mongo_client.py", line 1917, in _run_operation
    return self._retryable_read(
           ~~~~~~~~~~~~~~~~~~~~^
        _cmd,
        ^^^^^
    ...<4 lines>...
        operation=operation.name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/synchronous/mongo_client.py", line 2026, in _retryable_read
    return self._retry_internal(
           ~~~~~~~~~~~~~~~~~~~~^
        func,
        ^^^^^
    ...<7 lines>...
        operation_id=operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/_csot.py", line 125, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/synchronous/mongo_client.py", line 1993, in _retry_internal
    ).run()
      ~~~^^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/synchronous/mongo_client.py", line 2730, in run
    return self._read() if self._is_read else self._write()
           ~~~~~~~~~~^^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/synchronous/mongo_client.py", line 2875, in _read
    self._server = self._get_server()
                   ~~~~~~~~~~~~~~~~^^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/synchronous/mongo_client.py", line 2823, in _get_server
    return self._client._select_server(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._server_selector,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        operation_id=self._operation_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/synchronous/mongo_client.py", line 1812, in _select_server
    server = topology.select_server(
        server_selector,
    ...<2 lines>...
        operation_id=operation_id,
    )
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/synchronous/topology.py", line 409, in select_server
    server = self._select_server(
        selector,
    ...<4 lines>...
        operation_id=operation_id,
    )
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/synchronous/topology.py", line 387, in _select_server
    servers = self.select_servers(
        selector, operation, server_selection_timeout, address, operation_id
    )
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/synchronous/topology.py", line 294, in select_servers
    server_descriptions = self._select_servers_loop(
        selector, server_timeout, operation, operation_id, address
    )
  File "/home/ubuntu/.local/lib/python3.13/site-packages/pymongo/synchronous/topology.py", line 344, in _select_servers_loop
    raise ServerSelectionTimeoutError(
        f"{self._error_message(selector)}, Timeout: {timeout}s, Topology Description: {self.description!r}"
    )
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 68915dc46489e69950af30ee, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
